### ISSUE TITLE
Error when running feature

### ISSUE THREAD

**Issue by TheManFran** [AndrewKeig/protractor-cucumber#22]
I'm trying to run your example feature, but is getting a selenium error. Please see below.

c:\...\node_modules\protractor-cucumber\node_modules\selenium-webdriver\builder.js:407
    throw TypeError(
          ^
TypeError: Target browser must be a string, but is <object>; did you forget to call forBrowser()?
  at TypeError (<anonymous>:null:null)
  at [object Object].Builder.build (c:\...\node_modules\protractor-cucumber\node_modules\selenium-webdriver\builder.js:407:11)
  at new World (c:\...\node_modules\protractor-cucumber\lib\index.js:17:6)
  at Object.<anonymous> (c:\...\AppData\Roaming\npm\node_modules\cucumber\bin\cucumber.js:4:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

**Comment by laukev7** [comment]
Hi,

I submitted a pull request for this problem here:

https://github.com/AndrewKeig/protractor-cucumber/pull/21

**Comment by rudenoise** [comment]
Can confirm that this works, please merge.

**Comment by laukev7** [comment]
I sent an email to the maintainer, since we have two open issues on this already.

**Comment by AndrewKeig** [comment]
Apologies for the wait, this is not on npm.  Thanks.
