### ISSUE TITLE
getting a no file or directory issue when running 'cucumber.js' command

### ISSUE THREAD

**Issue by sheeralal** [AndrewKeig/protractor-cucumber#42]
fs.js:887
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/Users/sheeralal/projects/protractor-cucumber/features'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at Object.realpathSync (fs.js:1518:21)
    at Object.expandPathWithExtensions (/Users/sheeralal/projects/protractor-cucumber/node_modules/cucumber/lib/cucumber/cli/path_expander.js:14:23)
    at /Users/sheeralal/projects/protractor-cucumber/node_modules/cucumber/lib/cucumber/cli/path_expander.js:8:27
    at Array.map (native)
    at Object.expandPathsWithExtensions (/Users/sheeralal/projects/protractor-cucumber/node_modules/cucumber/lib/cucumber/cli/path_expander.js:7:31)
    at Object.expandPaths (/Users/sheeralal/projects/protractor-cucumber/node_modules/cucumber/lib/cucumber/cli/feature_path_expander.js:9:38)
    at Function.Configuration (/Users/sheeralal/projects/protractor-cucumber/node_modules/cucumber/lib/cucumber/cli/configuration.js:21:63)
    at getConfiguration (/Users/sheeralal/projects/protractor-cucumber/node_modules/cucumber/lib/cucumber/cli.js:48:38)

**Comment by ConsultDarryl** [comment]
Switch to the "example" folder: `cd Example` or run `cucumber-js example`

**Comment by RaghuramanKesavan** [comment]
Cucumber by default looks for "feature" folder in your project directory. either you can copy paste the feature present in the example folder to project directory or you can follow above mentioned method.
