### ISSUE TITLE
TypeError: protractor.wrapDriver is not a function

### ISSUE THREAD

**Issue by ConsultDarryl** [AndrewKeig/protractor-cucumber#45]
When you run "cucumber-js". If you see this error: 

TypeError: protractor.wrapDriver is not a function
    at new World (C:\Repos\protractor-cucumber\lib\index.js:27:31)
    at nextTickCallbackWith0Args (node.js:420:9)

This means you are using protractor version 4.0.0.

To fix... open package.json and change 
`"protractor": ">=1.6.0",` to `"protractor": "^3.2.0",`. Save the file. Run `npm install`

**Comment by floribon** [comment]
Protractor is now 4.0.3, I'd love to see a way to make it compatible with cucumber. If anyone has an idea please share it

**Comment by floribon** [comment]
I figured out how to support protractor 4 and created a PR if anyone is interested: https://github.com/AndrewKeig/protractor-cucumber/pull/47

**Comment by mobidev111** [comment]
@AndrewKeig could you merge #47? Would be of great to have the newer protractor versions working.
